FROM rocker/geospatial:4.4.1

# Will copy the package to the container preserving the directory structure
COPY . pkg/

# Installing missing dependencies
RUN r --vanilla -e 'remotes::install_deps(pkgdir = "pkg")'

CMD ["bash"]
