[project]
name = "cfa-epinow2-pipeline"
version = "0.2.0"
description = "CFA Epinow2 Pipeline"
readme = "README.md"
authors = [
    { name = "Kelly Reagan" }
]
requires-python = ">=3.13.2,<3.14"
dependencies = [
    "pyyaml~=6.0.2",
    "azure-identity~=1.25.1",
    "msrest~=0.7.1",
    "azure-mgmt-appcontainers~=4.0.0",
    "azure-mgmt-subscription~=3.1.1",
    "aiofiles~=24.1.0",
    "azure-keyvault-secrets",
    "cfa-dagster",
    "cfa-config-generator",
]


[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
]
[dependency-groups]
dev = [
    "cfa-dagster[dev]"
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "cfa_epinow2_pipeline"
defs_module = "cfa_epinow2_pipeline.dg_defs"
code_location_target_module = "cfa_epinow2_pipeline.dg_defs"

[tool.uv.sources]
# cfa-dagster = { git = "https://github.com/cdcgov/cfa-dagster", rev = "v1.4.3" }
cfa-dagster = { git = "https://github.com/cdcgov/cfa-dagster", rev = "gio-flex-defs" }
cfa-config-generator = { git = "https://github.com/cdcgov/cfa-config-generator.git" }
