name: Build Dependencies Container Image
run-name: (1) Dependencies Image Build - ${{ github.event.head_commit.message }} - ${{ github.ref_name }}

# This GitHub Actions workflow builds a Dependencies Docker image for the
# cfa-epinow2-pipeline-docker project. 
#
# - The `build_image_dependencies` job carries out the first part of a
#   multi-stage build. It downloads and installs all the dependencies
#   listed in the `DESCRIPTION` file. It uses the `Dockerfile-dependencies`
#   file to build the image.
#
#   The built image is then pushed to the corresponding registry.
#
#   The process is cached to avoid rebuilding the image if the dependencies
#   have not changed. This is by hashing the `DESCRIPTION` file and the
#   `Dockerfile-dependencies` file.

# - This built docker image is then referenced by the simply named 'Dockerfile', built in: 
#     - "2_pre-Test-Model-Image-Build" and 
#     - "2-Run-Epinow2-Pipeline.yaml"

on:
  push:
    branches:
      - main
    paths:
      - "./Dockerfile-dependencies" # the dockerfile this workflow builds from
      - "./.github/workflows/build-dependency-image.yaml" # this workflow

  pull_request:
    branches:
      - main
    paths:
      - "./Dockerfile-dependencies" # the dockerfile this workflow builds from
      - "./.github/workflows/build-dependency-image.yaml" # this workflow

  workflow_dispatch:

env:
  # Together, these form: cfaprdbatchcr.azurecr.io/cfa-epinow2-pipeline
  REGISTRY: cfaprdbatchcr.azurecr.io
  IMAGE_NAME: cfa-epinow2-pipeline

jobs:
  Job01-build_image_dependencies:
    runs-on: cfa-cdcgov # VM based runner serving CFA's cdcgov repos (as opposed to cdcent)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check cache
        uses: actions/cache@v3
        id: cache
        with:
          key: docker-dependencies-${{ runner.os }}-${{ hashFiles('./DESCRIPTION', './Dockerfile-dependencies') }}
          path:
            ./DESCRIPTION

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: "cfaprdbatchcr.azurecr.io"
          username: "cfaprdbatchcr"
          password: ${{ secrets.CFAPRDBATCHCR_REGISTRY_PASSWORD }}

      - name: Build and push
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}-dependencies:latest
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}-dependencies:${{ github.sha }}
          file: ./Dockerfile-dependencies
