name: Run Epinow2 Pipeline
run-name: (2) Epinow2 Pipeline - ${{ github.event.head_commit.message }} - ${{ github.ref_name }}

# This GitHub Actions workflow builds a Docker image for the
# cfa-epinow2-pipeline-docker project. It consists of two jobs:
# build_image_dependencies and build_image.
#
# - The `build_image_dependencies` job carries out the first part of a
#   multi-stage build. It downloads and install all the dependencies
#   listed in the `DESCRIPTION` file. It uses the `Dockerfile-dependencies`
#   file to build the image.
#
#   The built image is then pushed to the corresponding registry.
#
#   The process is cached to avoid rebuilding the image if the dependencies
#   have not changed. This is by hashing the `DESCRIPTION` file and the
#   `Dockerfile-dependencies` file.
#
# - The build_image job builds the final image using the `Dockerfile` file.
#   It uses the image built in the previous job as a base image.
#
#   During the build process, the package is installed and built. Furthermore
#   the package is checked using `R CMD check` to ensure that it is working
#   correctly.
#
#   Once the image is built, it is pushed to the corresponding registry.


on:
  push:
    branches:
      - main
      - jk-azure-readiness # temporary
  workflow_dispatch:

env:
  # Together, these form: cfaprdbatchcr.azurecr.io/cfa-epinow2-pipeline
  REGISTRY: cfaprdbatchcr.azurecr.io
  IMAGE_NAME: cfa-epinow2-pipeline

jobs:

  # We now use a two-stage docker build (essentially), split across two dockerfiles.
  # TODO: Only run this if necessary, will need conditional job syntax
  # SEE also; ./.github/workflows/1-Build-Dependency-Image.yml

  # Job01_build-image-dependencies:
  #   runs-on: cfa-cdcgov
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Login to the Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: "cfaprdbatchcr.azurecr.io"
  #         username: "cfaprdbatchcr"
  #         password: ${{ secrets.CFAPRDBATCHCR_REGISTRY_PASSWORD }}

  #     - name: Build and push dependencies image # first stage
  #       id: build_and_push_dependencies_image
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: |
  #           ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}-dependencies:latest
  #           ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}-dependencies:${{ github.sha }}
  #         file: ./Dockerfile-dependencies # first stage Dockerfile


  Job02_build-model-image:
    runs-on: cfa-cdcgov
    steps:

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: "cfaprdbatchcr.azurecr.io"
          username: "cfaprdbatchcr"
          password: ${{ secrets.CFAPRDBATCHCR_REGISTRY_PASSWORD }}

      - name: Build and push model pipeline image for Azure batch # second stage, the actual payload
        id: build_and_push_model_image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile # second stage Dockerfile

  Job03_create-batch-pool-and-submit-jobs:
    runs-on: cfa-cdcgov
    needs:
      - Job02_build-model-image

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4

      - name: Login to Azure with NNH Service Principal
        id: azure_login_2
        uses: azure/login@v2
        with:
        # managed by EDAV. Contact Amit Mantri or Jon Kislin if you have issues.
          creds: ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP }}

      - name: Create cfa-epinow2-pipeline Pool
        id: create_batch_pool

        # Every Azure Batch Pool parameter can simply go here,
        # no python module or config toml necessary
        env:
          POOL_ID:           "cfa-epinow2-${{ github.sha }}" # version the pools with the github sha
          BATCH_ACCOUNT:     "cfaprdba"
          BATCH_ENDPOINT:    "https://cfaprdba.eastus.batch.azure.com/pools/cfa-epinow2"
          VM_IMAGE_TAG:      "canonical:0001-com-ubuntu-server-focal:20_04-lts"
          NODE_AGENT_SKU_ID: "batch.node.ubuntu 20.04"
          VM_SIZE:           "standard_a4m_v2"

          AUTO_SCALE_FORMULA: |
            "// In this example, the pool size is adjusted based on the number of tasks in the queue.
             // Note that both comments and line breaks are acceptable in formula strings.

             // Get pending tasks for the past 15 minutes.
             $samples = $ActiveTasks.GetSamplePercent(TimeInterval_Minute * 15);

             // If we have fewer than 70 percent data points, we use the last sample point, otherwise we use the maximum of last sample point and the history average.
             $tasks = $samples < 70 ? max(0, $ActiveTasks.GetSample(1)) :
             max( $ActiveTasks.GetSample(1), avg($ActiveTasks.GetSample(TimeInterval_Minute * 15)));

             // If number of pending tasks is not 0, set targetVM to pending tasks, otherwise half of current dedicated.
             $targetVMs = $tasks > 0 ? $tasks : max(0, $TargetDedicatedNodes / 2);

             // The pool size is capped at 120, if target VM value is more than that, set it to 120.
             cappedPoolSize = 120;
             $TargetDedicatedNodes = max(0, min($targetVMs, cappedPoolSize));

             // Set node deallocation mode - keep nodes active only until tasks finish
             $NodeDeallocationOption = taskcompletion;"

        # The call to the az cli that actually generates the pool
        run: |
          az batch pool create \
          --id ${{ env.POOL_ID }} \
          --image ${{ env.VM_IMAGE_TAG }} \
          --node-agent-sku-id ${{ env.NODE_AGENT_SKU_ID}} \
          --auto-scale-formula ${{ env.AUTOSCALE_FORMULA}} \
          --vm-size ${{ env.VM_SIZE }} \
          --account-name ${{ env.BATCH_ACCOUNT }}
          --account-endpoint ${{ env.BATCH_ENDPOINT }}

          # Let's get this var for the next step too
          echo "POOL_ID=${{ env.POOL_ID}}" >> $GITHUB_ENV

      # - name: legacy_test
      #   run: |
      #     az batch pool create --json-file ./cfa-epinow2-batch-pool-config.json


      - name: Submit azure batch job
        id: submit_batch_job
        run: |
          az batch job create --pool-id ${{ github.env.POOL_ID }}


