# This GitHub Actions workflow builds a Docker image for the
# cfa-epinow2-pipeline-docker project. It consists of two jobs:
# build_image_dependencies and build_image.
#
# - The `build_image_dependencies` job carries out the first part of a
#   multi-stage build. It downloads and install all the dependencies
#   listed in the `DESCRIPTION` file. It uses the `Dockerfile-dependencies`
#   file to build the image.
#
#   The built image is then pushed to the corresponding registry.
#
#   The process is cached to avoid rebuilding the image if the dependencies
#   have not changed. This is by hashing the `DESCRIPTION` file and the
#   `Dockerfile-dependencies` file.
#
# - The build_image job builds the final image using the `Dockerfile` file.
#   It uses the image built in the previous job as a base image.
#
#   During the build process, the package is installed and built. Furthermore
#   the package is checked using `R CMD check` to ensure that it is working
#   correctly.
#
#   Once the image is built, it is pushed to the corresponding registry.

name: Builds Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: gvegayon/cfa-epinow2-pipeline
  REGISTRY: docker.io

jobs:
  build_image_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check cache
        uses: actions/cache@v3
        id: cache
        with:
          key: docker-dependencies-${{ runner.os }}-${{ hashFiles('./DESCRIPTION', './Dockerfile-dependencies') }}
          path:
            ./DESCRIPTION

      - name: Build and push
        uses: docker/build-push-action@v6
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          push: false
          tags: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile-dependencies

    outputs:
      IMAGE_NAME: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest

  build_image:
    needs: build_image_dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ needs.build_image_dependencies.outputs.IMAGE_NAME }}
          file: ./Dockerfile
