name: Tear down Batch pool

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:

  delete-pool:
    runs-on: cfa-cdcgov-aca
    name: Delete Batch pool

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

        # From: https://stackoverflow.com/a/58035262/2097171
      - name: Extract tag
        shell: bash
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: branch-name

      - name: Azure login
        id: azure_login_2
        uses: azure/login@v2
        with:
        # managed by EDAV. Contact Amit Mantri or Jon Kislin if you have issues.
          creds: ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP }}

      - name: Delete pool
        uses: azure/cli@v2
        run: |
            chmod +x $GITHUB_WORKSPACE/.github/scripts/cleanup-on-pr-close.sh
            $GITHUB_WORKSPACE/.github/scripts/cleanup-on-pr-close.sh \
              "${{ secrets.BATCH_ACCOUNT }}" \
              "${{ secrets.PRD_RESOURCE_GROUP }}" \
              "cfa-epinow2-${{ steps.branch-name.outputs.tag }}"
