name: Tear down Batch pool

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:

  delete-pool:
    runs-on: ubuntu-latest
    name: Delete Batch pool

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

        # From: https://stackoverflow.com/a/58035262/2097171
      - name: Extract tag
        shell: bash
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: branch-name

      - name: Delete pool
        uses: CDCgov/cfa-actions/runner-action@runner-action
        with:
          github_app_id: ${{ secrets.CDCENT_ACTOR_APP_ID }}
          github_app_pem: ${{ secrets.CDCENT_ACTOR_APP_PEM }}
          wait_for_completion: true
          print_logs: true
          script: |
            echo "Cloning repo at branch '$CURRENT_BRANCH'"
            git clone -b "$CURRENT_BRANCH" https://github.com/${{ github.repository }}.git
            cd cfa-epinow2-pipeline

            echo "Login to Azure with NNH Service Principal"
            az login --service-principal \
            --username ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientId }} \
            --password ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientSecret }} \
            --tenant ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).tenantId }}

            chmod +x ./.github/scripts/cleanup-on-pr-close.sh

            echo "Delete pool"
            ./.github/scripts/cleanup-on-pr-close.sh \
              "${{ secrets.BATCH_ACCOUNT }}" \
              "${{ secrets.PRD_RESOURCE_GROUP }}" \
              "cfa-epinow2-${{ steps.branch-name.outputs.tag }}"
