name: Delete tag from container registry

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

env:
  IMAGE_NAME: cfa-epinow2-pipeline

jobs:
  delete-container:
    runs-on: ubuntu-latest
    name: Deleting the container

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Delete Container Tag
        uses: CDCgov/cfa-actions/runner-action@runner-action
        with:
          github_app_id: ${{ secrets.CDCENT_ACTOR_APP_ID }}
          github_app_pem: ${{ secrets.CDCENT_ACTOR_APP_PEM }}
          wait_for_completion: true
          print_logs: true
          script: |
            echo "Cloning repo at branch '$CURRENT_BRANCH'"
            git clone -b "$CURRENT_BRANCH" https://github.com/${{ github.repository }}.git
            cd cfa-epinow2-pipeline

            echo "Login to Azure with NNH Service Principal"
            az login --service-principal \
            --username ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientId }} \
            --password ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).clientSecret }} \
            --tenant ${{ fromJSON(secrets.EDAV_CFA_PREDICT_NNHT_SP).tenantId }}

            chmod +x ./.github/scripts/delete-container-tag.sh

            echo "Delete container tag"
            ./.github/scripts/delete-container-tag.sh \
              ${{ secrets.CONTAINER_REGISTRY_URL }} \
              ${{ env.IMAGE_NAME }} \
              ${{ steps.image-tag.outputs.tag }}
