name: Pre-checkout work delete test

# This is a temporary template workflow that is used as a proof of concept 
# to clear the workspace to prevent checkout action errors.

on:
  workflow_dispatch:

jobs:

  delete-work-and-checkout:
    runs-on: cfa-cdcgov
    steps:

      - name: 'Cleanup runtime workspace folder'
        run: |
          echo "Current state of the runtime workspace folder:"
          ls -la ./
          echo ""
          echo "Our runtime workspace folder is located here:"
          pwd
          echo ""
          echo "Force deleting everything in the folder..."
          echo "First trying without sudo..."
          echo ""
          rm -rf ./* || true
          echo ""
          echo "State after running without sudo:"
          echo ""
          ls -la ./
          echo ""
          echo "Now trying with sudo..."
          echo ""
          echo ${{ secrets.CFA_AUTOMATED_JOBS }} | sudo -S rm -rfv ./* # recursive, forced, verbose
          echo ${{ secrets.CFA_AUTOMATED_JOBS }} | sudo -S rm -rfv ./.??* # recursive, forced, verbose
          echo "State after running with sudo:"
          echo ""
          ls -la ./

      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Post checkout inspection'
        run: |
          ls -la ./
          pwd
