name: Delete tag from container registry

on:
  pull_request:
    types: [closed]

env:
  IMAGE_NAME: cfa-epinow2-pipeline

jobs:
  delete-container:
    runs-on: cfa-cdcgov
    name: Deleting the container

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT


      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CFAPRDBATCHCR_REGISTRY_PASSWORD }}

      - name: Login to Azure with NNH Service Principal
        id: azure_login_2
        uses: azure/login@v2
        with:
          # managed by EDAV. Contact Amit Mantri or Jon Kislin if you
          # have issues. Also, this is documented in the Predict
          # handbook.
          creds: ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/.github/scripts/cleanup-tags-on-pr-close.sh
            $GITHUB_WORKSPACE/.github/scripts/cleanup-tags-on-pr-close.sh ${{ secrets.BATCH_ACCOUNT_NAME }} ${{ secrets.RESOURCE_GROUP }} ${{ secrets.CONTAINER_REGISTRY_URL }} ${{ env.IMAGE_NAME }} ${{ steps.image-tag.outputs.tag }}
