name: Pre-checkout work delete test

on:
  push:
  workflow_dispatch:

jobs:

  delete-work-and-checkout:
    runs-on: cfa-cdcgov
    steps:

      - name: 'Cleanup runtime workspace folder'
        run: |
          ls -la ./
          pwd
          echo ${{ secrets.CFA_AUTOMATED_JOBS }} | sudo -S rm -rf ./*
          # echo ${{ secrets.CFA_AUTOMATED_JOBS }} | sudo -S rm -rf ./.??*
          ls -la ./

      - name: Checkout
        uses: actions/checkout@v4


      - name: 'Post checkout inspection'
        run: |
          ls -la ./
          pwd
