# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R CMD check

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-image-name:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.image-name.outputs.image_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch-name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: |
          if [ "${{ steps.branch-name.outputs.branch }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image String
        id: image-name
        run: echo "image_name=ghcr.io/cdcgov/cfa-epinow2-pipeline:${{ steps.image-tag.outputs.tag }}" >> $GITHUB_OUTPUT

  R-CMD-check:
    runs-on: ubuntu-latest
    needs: get-image-name

    container:
      image: ${{ needs.get-image-name.outputs.IMAGE }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Check that roxygen documentation is up to date
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          Rscript -e "roxygen2::roxygenize()"
          git diff --exit-code man || (echo "::error::Documentation is not up to date. Run 'roxygen2::roxygenize()' locally to re-render." && exit 1)

      - name: R CMD Check
        run: |
          R CMD build --no-build-vignettes --no-manual . && \
          R CMD INSTALL CFAEpiNow2Pipeline_*.tar.gz && \
          R CMD check --no-build-vignettes --no-manual CFAEpiNow2Pipeline_*.tar.gz
      #- uses: r-lib/actions/check-r-package@v2
      #  with:
      #    upload-snapshots: true
      #    build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
