# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R CMD check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          # Dropping these for now because we deploy only on Ubuntu.
          # Ucomment as needed if supporting additional environments.
          #- {os: macos-latest,   r: 'release'}
          #- {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Investigate _temp/Library cmdstan
        run: |
          ls -a /home/runner/work/_temp/Library | grep cmdstan

      - name: Investigate _temp/Library cmdstanr
        run: |
          ls -a /home/runner/work/_temp/Library/cmdstanr

      - name: Investigate site-library
        run: |
          ls /opt/R/4.4.3/lib/R/site-library

      - run: |
          Rscript -e 'cmdstanr::install_cmdstan()' && \
            Rscript -e 'cmdstanr::set_cmdstan_path()' && \
            R CMD build --no-build-vignettes --no-manual . && \
            R CMD INSTALL CFAEpiNow2Pipeline_*.tar.gz && \
            R CMD check --no-build-vignettes --no-manual CFAEpiNow2Pipeline_*.tar.gz
