name: Start Container App Job
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash -ie {0}

jobs:
  start-caj:
    permissions:
      id-token: 'write'
      packages: 'read'
      contents: 'write'
    runs-on: cfa-cdcgov-aca
    name: start caj
    steps:
      - name: Azure login with OIDC
        id: azure_login_2
        uses: azure/login@v2
        with:
        # managed by EDAV. Contact Amit Mantri or Jon Kislin if you have issues.
          creds: ${{ secrets.EDAV_CFA_PREDICT_NNHT_SP }}

      - name: Get container app job template
        run: az containerapp job show --name "cfa-epinow2-test-caj" --resource-group "ext-edav-cfa-prd" --query "properties.template" --output yaml > example-job-template.yaml

      - name: Update template with input value
        run: yq -iy '.containers[0].command[1] = "$CONFIG_FILE"' example-template.yaml

      - name: Run container app job
        run: az containerapp job start --resource-group  "ext-edav-cfa-prd" --name "cfa-epinow2-test-caj" --yaml example-job-template.yaml
