# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Code coverage

jobs:
  get-image-name:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.image-name.outputs.image_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch-name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Figure out tag (either latest if it is main or the branch name)
        id: image-tag
        run: |
          if [ "${{ steps.branch-name.outputs.branch }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker Image String
        id: image-name
        run: echo "image_name=ghcr.io/cdcgov/cfa-epinow2-pipeline:${{ steps.image-tag.outputs.tag }}" >> $GITHUB_OUTPUT

  test-coverage:
    runs-on: ubuntu-latest
    needs: get-image-name

    container:
      image: ${{ needs.get-image-name.outputs.IMAGE }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: ./.github/workflows/containers-and-az-pool.yaml

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Install cmdstan
        uses: epinowcast/actions/install-cmdstan@v1
        with:
          cmdstan-version: '2.36.0'
          num-cores: 2

      - name: Test coverage
        shell: Rscript {0}
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"),
            token = "${{ secrets.CODECOV_TOKEN }}"
          )

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
